print ("Alright I don't have much time so lets get this over with.")
print ("I am SCAI-42 and I'm here to ask you some questions.")

name = input ("Ok, what is your name?")
print (name,", Really? That's your name? Well it could always be worse, you could be named James.",)

print("So how old are you",name,"?")
age = input (" ")
print (age,"? So you're basically an old man. Well great, you better not die on me.",)

print("How many siblings do you have",name,"?")
fam = input (" ")
print ("Ha,",fam,"! Well that explains alot")

print ("Anyways lets move on to some other topics, You seem uncomfortable.")
print ("What do like like to do for fun?")
fun = input


