print ("Lesson 3 Lab Part 1:")

print ("Alright I don't have much time so lets get this over with.")
print ("I am SCAI-42 and I'm here to ask you some questions.")

name = input ("Ok, what is your name?")
print (name,", Really? That's your name? Well it could always be worse, you could be named James.",)
 
print("So how old are you ",name,"?")
age = input (" ")
print (age,"? So you're basically an old man. Well great, you better not die on me.",)

print("How many siblings do you have ",name,"?")
fam = input (" ")
print ("Ha, ",fam,"! Well that explains alot.")

print ("Anyways lets move on to another topic, You seem uncomfortable.")

print ("What do like like to do for fun?")
fun = input (" ")
print (fun," literally sounds like the most boring thing ever.")

music = input ("Is you taste in music as boring as your taste in fun? What genre is your favorite?")
print (music,"! Really? that is so... not cool. Its just to meh for my taste.")

work = input ("So, do you do anything other than be boring in with your free time? Do you have a job?")
print ("Well I sure wouldn't want to be a", work,". But it pays the bills I guess.")

print ("So, your name is ",name," and you're ",age," stuck with ",fam," siblings. Your life life appears to be going nowhere as you are ",work," for a job, and for some reason you find ",fun," fun and ",music,"a good genre. I'm just kidding with you man, you seem like a cool dude. Good luck!")
