print("         __.....__          ")
print("      .-'         '-.       ")
print("    .'               '.     ")
print("   /                   \\   ")
print("  /        |\\           \\ ")
print(" ;        |V \\_          ; ")
print(" |        |  . \\         ; ")
print(" ;        )   ,_\\        | ")
print(" ;       /    |          ;  ")
print("  \\     /     \\         / ")
print("   \\    |      \\       /  ")
print("    '.   \\      \\    .'   ")
print("      '-._|      \\ -'      ")
print("          |  |\\   |        ")
print(" ________/   |_'.  /________")
